-- V14 — Contract Fixed Rates & Customer Exchange Rates

-- 1. Create contract_fixed_rates table
CREATE TABLE finance.contract_fixed_rates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contract_id         BIGINT NOT NULL,
    source_currency_id  BIGINT NOT NULL,
    target_currency_id  BIGINT NOT NULL,
    rate                NUMERIC(18, 6) NOT NULL,
    rate_type           VARCHAR(30) NOT NULL,
    valid_from          DATE NOT NULL,
    valid_to            DATE,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_contract_fixed_rates PRIMARY KEY (id),
    CONSTRAINT fk_cfr_contract FOREIGN KEY (contract_id) REFERENCES finance.contracts (id) ON DELETE CASCADE,
    CONSTRAINT fk_cfr_source_currency FOREIGN KEY (source_currency_id) REFERENCES finance.currencies (id),
    CONSTRAINT fk_cfr_target_currency FOREIGN KEY (target_currency_id) REFERENCES finance.currencies (id)
);

CREATE INDEX idx_cfr_lookup ON finance.contract_fixed_rates (contract_id, source_currency_id, target_currency_id, valid_from, valid_to);

-- 2. Create customer_exchange_rates table
CREATE TABLE finance.customer_exchange_rates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id         BIGINT NOT NULL,
    source_currency_id  BIGINT NOT NULL,
    target_currency_id  BIGINT NOT NULL,
    rate                NUMERIC(18, 6) NOT NULL,
    rate_type           VARCHAR(30) NOT NULL,
    rate_date           DATE NOT NULL,
    created_by          BIGINT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP,

    CONSTRAINT pk_customer_exchange_rates PRIMARY KEY (id),
    CONSTRAINT fk_cer_customer FOREIGN KEY (customer_id) REFERENCES finance.customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_cer_source_currency FOREIGN KEY (source_currency_id) REFERENCES finance.currencies (id),
    CONSTRAINT fk_cer_target_currency FOREIGN KEY (target_currency_id) REFERENCES finance.currencies (id),
    CONSTRAINT uk_customer_exchange_rates UNIQUE (customer_id, source_currency_id, target_currency_id, rate_date, rate_type)
);

CREATE INDEX idx_cer_lookup ON finance.customer_exchange_rates (customer_id, source_currency_id, target_currency_id, rate_date);

-- 3. Modify exchange_rate_audit_logs to make exchange_rate_id nullable and add contract_fixed_rate_id & customer_exchange_rate_id
ALTER TABLE finance.exchange_rate_audit_logs ALTER COLUMN exchange_rate_id DROP NOT NULL;

ALTER TABLE finance.exchange_rate_audit_logs ADD COLUMN contract_fixed_rate_id BIGINT;
ALTER TABLE finance.exchange_rate_audit_logs ADD COLUMN customer_exchange_rate_id BIGINT;

ALTER TABLE finance.exchange_rate_audit_logs
    ADD CONSTRAINT fk_eral_contract_fixed_rate
        FOREIGN KEY (contract_fixed_rate_id) REFERENCES finance.contract_fixed_rates (id) ON DELETE CASCADE;

ALTER TABLE finance.exchange_rate_audit_logs
    ADD CONSTRAINT fk_eral_customer_exchange_rate
        FOREIGN KEY (customer_exchange_rate_id) REFERENCES finance.customer_exchange_rates (id) ON DELETE CASCADE;

-- 4. Alter system_config to add strict_customer_rate flag
ALTER TABLE finance.system_config ADD COLUMN strict_customer_rate BOOLEAN NOT NULL DEFAULT FALSE;
