spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/wms-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://wms-keycloak:8080/realms/wms-realm/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: wms-kafka:9093
