-- =============================================================================
-- Flyway Migration: V24__notification_template_schema.sql
-- Çok Dilli Bildirim Şablonu Altyapısı (İş İsteri 2.1 — madde 5.2)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. notification_template
--    Dil bağımsız şablon üst kaydı.
--    channel : EMAIL | SMS | PUSH
-- -----------------------------------------------------------------------------
CREATE TABLE notification_template
(
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    template_code VARCHAR(100) NOT NULL,
    channel       VARCHAR(20)  NOT NULL,
    description   TEXT,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),

    CONSTRAINT pk_notification_template PRIMARY KEY (id),
    CONSTRAINT uq_notification_template_code UNIQUE (template_code),
    CONSTRAINT chk_notification_template_channel CHECK (channel IN ('EMAIL', 'SMS', 'PUSH'))
);

CREATE INDEX idx_notification_template_code    ON notification_template (template_code);
CREATE INDEX idx_notification_template_channel ON notification_template (channel);
CREATE INDEX idx_notification_template_active  ON notification_template (active);

COMMENT ON TABLE  notification_template               IS 'Çok dilli bildirim şablonları — dil bağımsız üst kayıt';
COMMENT ON COLUMN notification_template.template_code IS 'Render çağrılarının sözleşme anahtarı (örn: RECEIPT_APPROVED_MAIL)';
COMMENT ON COLUMN notification_template.channel       IS 'Gönderim kanalı: EMAIL | SMS | PUSH';
COMMENT ON COLUMN notification_template.created_by    IS 'Kaydı oluşturan JWT subject';
COMMENT ON COLUMN notification_template.updated_by    IS 'Son değişikliği yapan JWT subject';

-- -----------------------------------------------------------------------------
-- 2. notification_template_content
--    Şablonun dil bazlı içerikleri. {{variable}} placeholder söz dizimi.
--    subject: EMAIL için zorunlu (uygulama katmanında enforce edilir).
-- -----------------------------------------------------------------------------
CREATE TABLE notification_template_content
(
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    template_id   BIGINT       NOT NULL,
    language_code VARCHAR(10)  NOT NULL,
    subject       VARCHAR(500),
    body          TEXT         NOT NULL,
    updated_at    TIMESTAMPTZ,
    updated_by    VARCHAR(255),

    CONSTRAINT pk_notification_template_content PRIMARY KEY (id),
    CONSTRAINT uq_ntc_template_language UNIQUE (template_id, language_code),
    CONSTRAINT fk_ntc_template FOREIGN KEY (template_id)
        REFERENCES notification_template (id) ON DELETE CASCADE
);

CREATE INDEX idx_ntc_template_id   ON notification_template_content (template_id);
CREATE INDEX idx_ntc_language_code ON notification_template_content (language_code);

COMMENT ON TABLE  notification_template_content               IS 'Bildirim şablonlarının dil bazlı içerikleri';
COMMENT ON COLUMN notification_template_content.language_code IS 'ISO 639-1 dil kodu — language.code ile eşleşir';
COMMENT ON COLUMN notification_template_content.body          IS 'Şablon gövdesi — {{variable}} placeholder söz dizimi';

-- -----------------------------------------------------------------------------
-- 3. missing_template_log
--    İstenen dilde içeriği bulunamayan şablon kayıtları
--    (missing_translation_log ile aynı desen).
-- -----------------------------------------------------------------------------
CREATE TABLE missing_template_log
(
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    locale        VARCHAR(10)  NOT NULL,
    template_code VARCHAR(100) NOT NULL,
    channel       VARCHAR(20),
    first_seen_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    hit_count     BIGINT       NOT NULL DEFAULT 1,
    resolved      BOOLEAN      NOT NULL DEFAULT FALSE,
    resolved_at   TIMESTAMPTZ,

    CONSTRAINT pk_missing_template_log PRIMARY KEY (id),
    CONSTRAINT uq_mtpl_locale_template UNIQUE (locale, template_code),
    CONSTRAINT chk_mtpl_hit_count CHECK (hit_count >= 1)
);

CREATE INDEX idx_mtpl_template_code ON missing_template_log (template_code);
CREATE INDEX idx_mtpl_locale        ON missing_template_log (locale);
CREATE INDEX idx_mtpl_resolved      ON missing_template_log (resolved);
CREATE INDEX idx_mtpl_last_seen     ON missing_template_log (last_seen_at DESC);

-- Admin dashboard için: çözümlenmemiş + en çok hit alan üstte
CREATE INDEX idx_mtpl_unresolved_hits
    ON missing_template_log (resolved, hit_count DESC)
    WHERE resolved = FALSE;

COMMENT ON TABLE  missing_template_log           IS 'İstenen dilde içeriği bulunamayan bildirim şablonu kayıtları';
COMMENT ON COLUMN missing_template_log.hit_count IS 'Kaç kez eksik bulundu — önceliklendirme için';
COMMENT ON COLUMN missing_template_log.resolved  IS 'İçerik upsert edildiğinde otomatik işaretlenir';
