-- =====================================================================
-- V16: UUID → BIGINT primary key / foreign key migration
-- PostgreSQL 16 — wms_core_db
--
-- Converts all UUID PK/FK columns listed below to BIGINT while preserving
-- row data and relationships via id_legacy_map.
-- =====================================================================

BEGIN;

-- -----------------------------------------------------------------------
-- Legacy UUID → BIGINT mapping table
-- -----------------------------------------------------------------------
CREATE TABLE id_legacy_map (
    entity_type VARCHAR(50) NOT NULL,
    old_uuid    UUID        NOT NULL,
    new_id      BIGINT      NOT NULL,
    PRIMARY KEY (entity_type, old_uuid)
);

CREATE INDEX idx_id_legacy_map_new_id ON id_legacy_map (entity_type, new_id);

-- -----------------------------------------------------------------------
-- Helper: populate id_bigint + id_legacy_map for a table PK
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_migrate_uuid_pk(
    p_table       TEXT,
    p_entity_type VARCHAR(50),
    p_order_by    TEXT
) RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format(
        'ALTER TABLE %I ADD COLUMN id_bigint BIGINT',
        p_table
    );

    EXECUTE format(
        'UPDATE %I t
            SET id_bigint = ranked.new_id
           FROM (
               SELECT id AS old_id,
                      ROW_NUMBER() OVER (ORDER BY %s) AS new_id
                 FROM %I
           ) ranked
          WHERE t.id = ranked.old_id',
        p_table, p_order_by, p_table
    );

    EXECUTE format(
        'INSERT INTO id_legacy_map (entity_type, old_uuid, new_id)
         SELECT %L, id, id_bigint FROM %I',
        p_entity_type, p_table
    );
END;
$$;

-- -----------------------------------------------------------------------
-- Helper: add/populate a FK column from id_legacy_map
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_migrate_uuid_fk(
    p_table       TEXT,
    p_column      TEXT,
    p_entity_type VARCHAR(50)
) RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format(
        'ALTER TABLE %I ADD COLUMN %I BIGINT',
        p_table, p_column || '_bigint'
    );

    EXECUTE format(
        'UPDATE %I t
            SET %I = m.new_id
           FROM id_legacy_map m
          WHERE m.entity_type = %L
            AND m.old_uuid = t.%I',
        p_table, p_column || '_bigint', p_entity_type, p_column
    );
END;
$$;

-- -----------------------------------------------------------------------
-- Helper: finalize PK — drop UUID id, promote id_bigint, add IDENTITY
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_finalize_uuid_pk(p_table TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_max_id BIGINT;
BEGIN
    EXECUTE format(
        'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
        p_table, p_table || '_pkey'
    );
    EXECUTE format('ALTER TABLE %I DROP COLUMN id', p_table);
    EXECUTE format('ALTER TABLE %I RENAME COLUMN id_bigint TO id', p_table);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET NOT NULL', p_table);
    EXECUTE format('ALTER TABLE %I ADD PRIMARY KEY (id)', p_table);
    EXECUTE format(
        'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
        p_table
    );

    EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I', p_table) INTO v_max_id;
    IF v_max_id > 0 THEN
        PERFORM setval(pg_get_serial_sequence(p_table, 'id'), v_max_id);
    END IF;
END;
$$;

-- -----------------------------------------------------------------------
-- Helper: finalize FK — drop UUID column, promote *_bigint column
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_finalize_uuid_fk(p_table TEXT, p_column TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format('ALTER TABLE %I DROP COLUMN %I', p_table, p_column);
    EXECUTE format(
        'ALTER TABLE %I RENAME COLUMN %I TO %I',
        p_table, p_column || '_bigint', p_column
    );
END;
$$;

-- -----------------------------------------------------------------------
-- Helper: map configuration_audit_logs.entity_name → id_legacy_map.entity_type
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_audit_entity_type(p_entity_name VARCHAR(100))
RETURNS VARCHAR(50)
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE p_entity_name
        WHEN 'Organization'              THEN 'organization'
        WHEN 'organization'              THEN 'organization'
        WHEN 'organizations'             THEN 'organization'
        WHEN 'Company'                   THEN 'company'
        WHEN 'company'                   THEN 'company'
        WHEN 'companies'                 THEN 'company'
        WHEN 'Country'                   THEN 'country'
        WHEN 'country'                   THEN 'country'
        WHEN 'countries'                 THEN 'country'
        WHEN 'Region'                    THEN 'region'
        WHEN 'region'                    THEN 'region'
        WHEN 'regions'                   THEN 'region'
        WHEN 'StateProvince'             THEN 'state_province'
        WHEN 'state_province'            THEN 'state_province'
        WHEN 'state_provinces'           THEN 'state_province'
        WHEN 'City'                      THEN 'city'
        WHEN 'city'                      THEN 'city'
        WHEN 'cities'                    THEN 'city'
        WHEN 'District'                  THEN 'district'
        WHEN 'district'                  THEN 'district'
        WHEN 'districts'                 THEN 'district'
        WHEN 'Neighborhood'              THEN 'neighborhood'
        WHEN 'neighborhood'              THEN 'neighborhood'
        WHEN 'neighborhoods'             THEN 'neighborhood'
        WHEN 'User'                      THEN 'user'
        WHEN 'user'                      THEN 'user'
        WHEN 'users'                     THEN 'user'
        WHEN 'Role'                      THEN 'role'
        WHEN 'role'                      THEN 'role'
        WHEN 'roles'                     THEN 'role'
        WHEN 'Location'                  THEN 'location'
        WHEN 'location'                  THEN 'location'
        WHEN 'locations'                 THEN 'location'
        WHEN 'Zone'                      THEN 'zone'
        WHEN 'zone'                      THEN 'zone'
        WHEN 'zones'                     THEN 'zone'
        WHEN 'UserAccess'                THEN 'user_access'
        WHEN 'user_access'               THEN 'user_access'
        WHEN 'user_accesses'             THEN 'user_access'
        WHEN 'TransactionLog'            THEN 'transaction_log'
        WHEN 'transaction_log'           THEN 'transaction_log'
        WHEN 'transaction_logs'          THEN 'transaction_log'
        WHEN 'ProcessDefinition'         THEN 'process_definition'
        WHEN 'process_definition'        THEN 'process_definition'
        WHEN 'process_definitions'       THEN 'process_definition'
        WHEN 'ProcessStepDefinition'     THEN 'process_step_definition'
        WHEN 'process_step_definition'   THEN 'process_step_definition'
        WHEN 'process_step_definitions'  THEN 'process_step_definition'
        WHEN 'LocationProcessConfig'     THEN 'location_process_config'
        WHEN 'location_process_config'   THEN 'location_process_config'
        WHEN 'location_process_configs'  THEN 'location_process_config'
        WHEN 'LocationProcessStepConfig' THEN 'location_process_step_config'
        WHEN 'location_process_step_config'  THEN 'location_process_step_config'
        WHEN 'location_process_step_configs' THEN 'location_process_step_config'
        WHEN 'ConfigurationAuditLog'     THEN 'configuration_audit_log'
        WHEN 'configuration_audit_log'   THEN 'configuration_audit_log'
        WHEN 'configuration_audit_logs'  THEN 'configuration_audit_log'
        WHEN 'ApprovalRequest'           THEN 'approval_request'
        WHEN 'approval_request'          THEN 'approval_request'
        WHEN 'approval_requests'         THEN 'approval_request'
        WHEN 'Stock'                     THEN 'stock'
        WHEN 'stock'                     THEN 'stock'
        WHEN 'stocks'                    THEN 'stock'
        WHEN 'Screen'                    THEN 'screen'
        WHEN 'screen'                    THEN 'screen'
        WHEN 'screens'                   THEN 'screen'
        WHEN 'ScreenField'               THEN 'screen_field'
        WHEN 'screen_field'              THEN 'screen_field'
        WHEN 'screen_fields'             THEN 'screen_field'
        WHEN 'FieldBehaviorRule'         THEN 'field_behavior_rule'
        WHEN 'field_behavior_rule'       THEN 'field_behavior_rule'
        WHEN 'field_behavior_rules'      THEN 'field_behavior_rule'
        WHEN 'StorageLocation'           THEN 'storage_location'
        WHEN 'storage_location'          THEN 'storage_location'
        WHEN 'storage_locations'         THEN 'storage_location'
        ELSE NULL
    END;
$$;

-- ===================================================================
-- PHASE 1 — Assign BIGINT PKs (dependency order) + legacy map rows
-- ===================================================================

SELECT wms_migrate_uuid_pk('organizations',              'organization',              'created_at, id');
SELECT wms_migrate_uuid_pk('companies',                  'company',                   'created_at, id');
SELECT wms_migrate_uuid_pk('countries',                  'country',                   'created_at, id');
SELECT wms_migrate_uuid_pk('regions',                    'region',                    'created_at, id');
SELECT wms_migrate_uuid_pk('state_provinces',           'state_province',            'created_at, id');
SELECT wms_migrate_uuid_pk('cities',                     'city',                      'created_at, id');
SELECT wms_migrate_uuid_pk('districts',                  'district',                  'created_at, id');
SELECT wms_migrate_uuid_pk('neighborhoods',              'neighborhood',              'created_at, id');
SELECT wms_migrate_uuid_pk('users',                      'user',                      'created_at, id');
SELECT wms_migrate_uuid_pk('roles',                      'role',                      'created_at, id');
SELECT wms_migrate_uuid_pk('locations',                  'location',                  'created_at, id');
SELECT wms_migrate_uuid_pk('zones',                      'zone',                      'created_at, id');
SELECT wms_migrate_uuid_pk('user_accesses',              'user_access',               'id');
SELECT wms_migrate_uuid_pk('transaction_logs',           'transaction_log',           'created_at_utc, id');
SELECT wms_migrate_uuid_pk('process_definitions',        'process_definition',        'created_at, id');
SELECT wms_migrate_uuid_pk('process_step_definitions',   'process_step_definition',   'created_at, id');
SELECT wms_migrate_uuid_pk('location_process_configs',   'location_process_config',   'created_at, id');
SELECT wms_migrate_uuid_pk('location_process_step_configs', 'location_process_step_config', 'created_at, id');
SELECT wms_migrate_uuid_pk('configuration_audit_logs',     'configuration_audit_log',   'changed_at, id');
SELECT wms_migrate_uuid_pk('approval_requests',          'approval_request',          'created_at, id');
SELECT wms_migrate_uuid_pk('stocks',                     'stock',                     'created_at, id');
SELECT wms_migrate_uuid_pk('screens',                    'screen',                    'created_at, id');
SELECT wms_migrate_uuid_pk('screen_fields',              'screen_field',              'created_at, id');
SELECT wms_migrate_uuid_pk('field_behavior_rules',       'field_behavior_rule',       'COALESCE(updated_at, TIMESTAMPTZ ''1970-01-01''), id');
SELECT wms_migrate_uuid_pk('storage_locations',          'storage_location',          'created_at, id');

-- ===================================================================
-- PHASE 2 — Populate BIGINT FK columns from id_legacy_map
-- ===================================================================

-- companies
SELECT wms_migrate_uuid_fk('companies', 'organization_id', 'organization');

-- regions
SELECT wms_migrate_uuid_fk('regions', 'country_id', 'country');

-- locations
SELECT wms_migrate_uuid_fk('locations', 'company_id', 'company');
SELECT wms_migrate_uuid_fk('locations', 'region_id', 'region');

-- zones
SELECT wms_migrate_uuid_fk('zones', 'location_id', 'location');

-- user_accesses
SELECT wms_migrate_uuid_fk('user_accesses', 'user_id', 'user');
SELECT wms_migrate_uuid_fk('user_accesses', 'company_id', 'company');
SELECT wms_migrate_uuid_fk('user_accesses', 'location_id', 'location');
SELECT wms_migrate_uuid_fk('user_accesses', 'role_id', 'role');

-- transaction_logs
SELECT wms_migrate_uuid_fk('transaction_logs', 'company_id', 'company');
SELECT wms_migrate_uuid_fk('transaction_logs', 'location_id', 'location');
SELECT wms_migrate_uuid_fk('transaction_logs', 'user_id', 'user');

-- state_provinces
SELECT wms_migrate_uuid_fk('state_provinces', 'country_id', 'country');

-- cities
SELECT wms_migrate_uuid_fk('cities', 'country_id', 'country');
SELECT wms_migrate_uuid_fk('cities', 'state_province_id', 'state_province');

-- districts
SELECT wms_migrate_uuid_fk('districts', 'city_id', 'city');

-- neighborhoods
SELECT wms_migrate_uuid_fk('neighborhoods', 'district_id', 'district');

-- process_step_definitions
SELECT wms_migrate_uuid_fk('process_step_definitions', 'process_definition_id', 'process_definition');

-- location_process_configs (location_id has no DB FK — still migrated)
SELECT wms_migrate_uuid_fk('location_process_configs', 'location_id', 'location');
SELECT wms_migrate_uuid_fk('location_process_configs', 'process_definition_id', 'process_definition');

-- location_process_step_configs
SELECT wms_migrate_uuid_fk('location_process_step_configs', 'location_process_config_id', 'location_process_config');
SELECT wms_migrate_uuid_fk('location_process_step_configs', 'process_step_definition_id', 'process_step_definition');
SELECT wms_migrate_uuid_fk('location_process_step_configs', 'responsible_role_id', 'role');

-- configuration_audit_logs — polymorphic entity_id + changed_by_user_id
ALTER TABLE configuration_audit_logs ADD COLUMN entity_id_bigint BIGINT;
ALTER TABLE configuration_audit_logs ADD COLUMN changed_by_user_id_bigint BIGINT;

UPDATE configuration_audit_logs cal
   SET entity_id_bigint = m.new_id
  FROM id_legacy_map m
 WHERE m.old_uuid = cal.entity_id
   AND m.entity_type = wms_audit_entity_type(cal.entity_name);

UPDATE configuration_audit_logs cal
   SET changed_by_user_id_bigint = m.new_id
  FROM id_legacy_map m
 WHERE cal.changed_by_user_id IS NOT NULL
   AND m.entity_type = 'user'
   AND m.old_uuid = cal.changed_by_user_id;

-- approval_requests
SELECT wms_migrate_uuid_fk('approval_requests', 'step_config_id', 'location_process_step_config');
SELECT wms_migrate_uuid_fk('approval_requests', 'requested_by_user_id', 'user');
SELECT wms_migrate_uuid_fk('approval_requests', 'approved_by_user_id', 'user');

-- reference_id: storage-type only (cross-service UUIDs — no legacy map join)
ALTER TABLE approval_requests ADD COLUMN reference_id_bigint BIGINT;

UPDATE approval_requests
   SET reference_id_bigint = (
       'x' || substr(replace(reference_id::text, '-', ''), 1, 16)
   )::bit(64)::bigint;

-- stocks
SELECT wms_migrate_uuid_fk('stocks', 'company_id', 'company');
SELECT wms_migrate_uuid_fk('stocks', 'location_id', 'location');

-- screen_fields
SELECT wms_migrate_uuid_fk('screen_fields', 'screen_id', 'screen');

-- field_behavior_rules (nullable context FKs — no DB constraints)
SELECT wms_migrate_uuid_fk('field_behavior_rules', 'screen_field_id', 'screen_field');
SELECT wms_migrate_uuid_fk('field_behavior_rules', 'company_id', 'company');
SELECT wms_migrate_uuid_fk('field_behavior_rules', 'country_id', 'country');
SELECT wms_migrate_uuid_fk('field_behavior_rules', 'location_id', 'location');
SELECT wms_migrate_uuid_fk('field_behavior_rules', 'role_id', 'role');

-- storage_locations
SELECT wms_migrate_uuid_fk('storage_locations', 'zone_id', 'zone');

-- ===================================================================
-- PHASE 3 — Integrity checks before destructive DDL
-- ===================================================================

DO $$
DECLARE
    v_unmapped_entity_ids BIGINT;
BEGIN
    SELECT COUNT(*) INTO v_unmapped_entity_ids
      FROM configuration_audit_logs
     WHERE entity_id_bigint IS NULL;

    IF v_unmapped_entity_ids > 0 THEN
        RAISE EXCEPTION
            'configuration_audit_logs: % row(s) have unmapped entity_id (unknown entity_name)',
            v_unmapped_entity_ids;
    END IF;

    IF EXISTS (
        SELECT 1
          FROM companies
         WHERE organization_id IS NOT NULL
           AND organization_id_bigint IS NULL
    ) THEN
        RAISE EXCEPTION 'companies.organization_id has unmapped UUID values';
    END IF;
END;
$$;

-- ===================================================================
-- PHASE 4 — Drop all UUID foreign key constraints
-- ===================================================================

ALTER TABLE companies                      DROP CONSTRAINT IF EXISTS fk_company_organization;
ALTER TABLE regions                        DROP CONSTRAINT IF EXISTS fk_region_country;
ALTER TABLE locations                      DROP CONSTRAINT IF EXISTS fk_location_company;
ALTER TABLE locations                      DROP CONSTRAINT IF EXISTS fk_location_region;
ALTER TABLE zones                          DROP CONSTRAINT IF EXISTS fk_zone_location;
ALTER TABLE user_accesses                  DROP CONSTRAINT IF EXISTS fk_user_access_user;
ALTER TABLE user_accesses                  DROP CONSTRAINT IF EXISTS fk_user_access_company;
ALTER TABLE user_accesses                  DROP CONSTRAINT IF EXISTS fk_user_access_location;
ALTER TABLE user_accesses                  DROP CONSTRAINT IF EXISTS fk_user_access_role;
ALTER TABLE transaction_logs               DROP CONSTRAINT IF EXISTS fk_txlog_company;
ALTER TABLE transaction_logs               DROP CONSTRAINT IF EXISTS fk_txlog_location;
ALTER TABLE transaction_logs               DROP CONSTRAINT IF EXISTS fk_txlog_user;
ALTER TABLE state_provinces               DROP CONSTRAINT IF EXISTS fk_state_province_country;
ALTER TABLE cities                         DROP CONSTRAINT IF EXISTS fk_city_country;
ALTER TABLE cities                         DROP CONSTRAINT IF EXISTS fk_city_state_province;
ALTER TABLE districts                      DROP CONSTRAINT IF EXISTS fk_district_city;
ALTER TABLE neighborhoods                  DROP CONSTRAINT IF EXISTS fk_neighborhood_district;
ALTER TABLE process_step_definitions       DROP CONSTRAINT IF EXISTS fk_step_def_process_def;
ALTER TABLE location_process_configs       DROP CONSTRAINT IF EXISTS fk_loc_proc_config_process_def;
ALTER TABLE location_process_step_configs  DROP CONSTRAINT IF EXISTS fk_step_config_loc_proc_config;
ALTER TABLE location_process_step_configs  DROP CONSTRAINT IF EXISTS fk_step_config_step_def;
ALTER TABLE stocks                         DROP CONSTRAINT IF EXISTS fk_stock_company;
ALTER TABLE stocks                         DROP CONSTRAINT IF EXISTS fk_stock_location;
ALTER TABLE screen_fields                  DROP CONSTRAINT IF EXISTS fk_screen_field_screen;
ALTER TABLE field_behavior_rules           DROP CONSTRAINT IF EXISTS fk_fbr_screen_field;
ALTER TABLE storage_locations              DROP CONSTRAINT IF EXISTS fk_sl_zone;

-- ===================================================================
-- PHASE 5 — Finalize PK columns (UUID id → BIGINT id + IDENTITY)
-- ===================================================================

SELECT wms_finalize_uuid_pk('organizations');
SELECT wms_finalize_uuid_pk('companies');
SELECT wms_finalize_uuid_pk('countries');
SELECT wms_finalize_uuid_pk('regions');
SELECT wms_finalize_uuid_pk('state_provinces');
SELECT wms_finalize_uuid_pk('cities');
SELECT wms_finalize_uuid_pk('districts');
SELECT wms_finalize_uuid_pk('neighborhoods');
SELECT wms_finalize_uuid_pk('users');
SELECT wms_finalize_uuid_pk('roles');
SELECT wms_finalize_uuid_pk('locations');
SELECT wms_finalize_uuid_pk('zones');
SELECT wms_finalize_uuid_pk('user_accesses');
SELECT wms_finalize_uuid_pk('transaction_logs');
SELECT wms_finalize_uuid_pk('process_definitions');
SELECT wms_finalize_uuid_pk('process_step_definitions');
SELECT wms_finalize_uuid_pk('location_process_configs');
SELECT wms_finalize_uuid_pk('location_process_step_configs');
SELECT wms_finalize_uuid_pk('configuration_audit_logs');
SELECT wms_finalize_uuid_pk('approval_requests');
SELECT wms_finalize_uuid_pk('stocks');
SELECT wms_finalize_uuid_pk('screens');
SELECT wms_finalize_uuid_pk('screen_fields');
SELECT wms_finalize_uuid_pk('field_behavior_rules');
SELECT wms_finalize_uuid_pk('storage_locations');

-- ===================================================================
-- PHASE 6 — Finalize FK columns (UUID → BIGINT)
-- ===================================================================

SELECT wms_finalize_uuid_fk('companies', 'organization_id');

SELECT wms_finalize_uuid_fk('regions', 'country_id');

SELECT wms_finalize_uuid_fk('locations', 'company_id');
SELECT wms_finalize_uuid_fk('locations', 'region_id');

SELECT wms_finalize_uuid_fk('zones', 'location_id');

SELECT wms_finalize_uuid_fk('user_accesses', 'user_id');
SELECT wms_finalize_uuid_fk('user_accesses', 'company_id');
SELECT wms_finalize_uuid_fk('user_accesses', 'location_id');
SELECT wms_finalize_uuid_fk('user_accesses', 'role_id');

SELECT wms_finalize_uuid_fk('transaction_logs', 'company_id');
SELECT wms_finalize_uuid_fk('transaction_logs', 'location_id');
SELECT wms_finalize_uuid_fk('transaction_logs', 'user_id');

SELECT wms_finalize_uuid_fk('state_provinces', 'country_id');

SELECT wms_finalize_uuid_fk('cities', 'country_id');
SELECT wms_finalize_uuid_fk('cities', 'state_province_id');

SELECT wms_finalize_uuid_fk('districts', 'city_id');

SELECT wms_finalize_uuid_fk('neighborhoods', 'district_id');

SELECT wms_finalize_uuid_fk('process_step_definitions', 'process_definition_id');

SELECT wms_finalize_uuid_fk('location_process_configs', 'location_id');
SELECT wms_finalize_uuid_fk('location_process_configs', 'process_definition_id');

SELECT wms_finalize_uuid_fk('location_process_step_configs', 'location_process_config_id');
SELECT wms_finalize_uuid_fk('location_process_step_configs', 'process_step_definition_id');
SELECT wms_finalize_uuid_fk('location_process_step_configs', 'responsible_role_id');

ALTER TABLE configuration_audit_logs DROP COLUMN entity_id;
ALTER TABLE configuration_audit_logs RENAME COLUMN entity_id_bigint TO entity_id;
ALTER TABLE configuration_audit_logs ALTER COLUMN entity_id SET NOT NULL;

ALTER TABLE configuration_audit_logs DROP COLUMN changed_by_user_id;
ALTER TABLE configuration_audit_logs RENAME COLUMN changed_by_user_id_bigint TO changed_by_user_id;

SELECT wms_finalize_uuid_fk('approval_requests', 'step_config_id');
SELECT wms_finalize_uuid_fk('approval_requests', 'requested_by_user_id');
SELECT wms_finalize_uuid_fk('approval_requests', 'approved_by_user_id');

ALTER TABLE approval_requests DROP COLUMN reference_id;
ALTER TABLE approval_requests RENAME COLUMN reference_id_bigint TO reference_id;
ALTER TABLE approval_requests ALTER COLUMN reference_id SET NOT NULL;

SELECT wms_finalize_uuid_fk('stocks', 'company_id');
SELECT wms_finalize_uuid_fk('stocks', 'location_id');

SELECT wms_finalize_uuid_fk('screen_fields', 'screen_id');

SELECT wms_finalize_uuid_fk('field_behavior_rules', 'screen_field_id');
SELECT wms_finalize_uuid_fk('field_behavior_rules', 'company_id');
SELECT wms_finalize_uuid_fk('field_behavior_rules', 'country_id');
SELECT wms_finalize_uuid_fk('field_behavior_rules', 'location_id');
SELECT wms_finalize_uuid_fk('field_behavior_rules', 'role_id');

SELECT wms_finalize_uuid_fk('storage_locations', 'zone_id');

-- ===================================================================
-- PHASE 7 — Re-create foreign key constraints (BIGINT)
-- ===================================================================

ALTER TABLE companies
    ADD CONSTRAINT fk_company_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE regions
    ADD CONSTRAINT fk_region_country
        FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE locations
    ADD CONSTRAINT fk_location_company
        FOREIGN KEY (company_id) REFERENCES companies (id),
    ADD CONSTRAINT fk_location_region
        FOREIGN KEY (region_id) REFERENCES regions (id);

ALTER TABLE zones
    ADD CONSTRAINT fk_zone_location
        FOREIGN KEY (location_id) REFERENCES locations (id);

ALTER TABLE user_accesses
    ADD CONSTRAINT fk_user_access_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_user_access_company
        FOREIGN KEY (company_id) REFERENCES companies (id),
    ADD CONSTRAINT fk_user_access_location
        FOREIGN KEY (location_id) REFERENCES locations (id),
    ADD CONSTRAINT fk_user_access_role
        FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE transaction_logs
    ADD CONSTRAINT fk_txlog_company
        FOREIGN KEY (company_id) REFERENCES companies (id),
    ADD CONSTRAINT fk_txlog_location
        FOREIGN KEY (location_id) REFERENCES locations (id),
    ADD CONSTRAINT fk_txlog_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE state_provinces
    ADD CONSTRAINT fk_state_province_country
        FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE cities
    ADD CONSTRAINT fk_city_country
        FOREIGN KEY (country_id) REFERENCES countries (id),
    ADD CONSTRAINT fk_city_state_province
        FOREIGN KEY (state_province_id) REFERENCES state_provinces (id);

ALTER TABLE districts
    ADD CONSTRAINT fk_district_city
        FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE neighborhoods
    ADD CONSTRAINT fk_neighborhood_district
        FOREIGN KEY (district_id) REFERENCES districts (id);

ALTER TABLE process_step_definitions
    ADD CONSTRAINT fk_step_def_process_def
        FOREIGN KEY (process_definition_id) REFERENCES process_definitions (id);

ALTER TABLE location_process_configs
    ADD CONSTRAINT fk_loc_proc_config_process_def
        FOREIGN KEY (process_definition_id) REFERENCES process_definitions (id);

ALTER TABLE location_process_step_configs
    ADD CONSTRAINT fk_step_config_loc_proc_config
        FOREIGN KEY (location_process_config_id) REFERENCES location_process_configs (id),
    ADD CONSTRAINT fk_step_config_step_def
        FOREIGN KEY (process_step_definition_id) REFERENCES process_step_definitions (id);

ALTER TABLE stocks
    ADD CONSTRAINT fk_stock_company
        FOREIGN KEY (company_id) REFERENCES companies (id),
    ADD CONSTRAINT fk_stock_location
        FOREIGN KEY (location_id) REFERENCES locations (id);

ALTER TABLE screen_fields
    ADD CONSTRAINT fk_screen_field_screen
        FOREIGN KEY (screen_id) REFERENCES screens (id) ON DELETE RESTRICT;

ALTER TABLE field_behavior_rules
    ADD CONSTRAINT fk_fbr_screen_field
        FOREIGN KEY (screen_field_id) REFERENCES screen_fields (id) ON DELETE CASCADE;

ALTER TABLE storage_locations
    ADD CONSTRAINT fk_sl_zone
        FOREIGN KEY (zone_id) REFERENCES zones (id);

-- configuration_audit_logs.changed_by_user_id — optional logical FK (no prior DB constraint)
-- approval_requests — no FK constraints in original schema

-- ===================================================================
-- PHASE 8 — Re-create indexes dropped with UUID FK columns
-- ===================================================================

CREATE INDEX idx_company_org              ON companies (organization_id);
CREATE INDEX idx_location_company         ON locations (company_id);
CREATE INDEX idx_location_region          ON locations (region_id);
CREATE INDEX idx_user_access_user         ON user_accesses (user_id);
CREATE INDEX idx_user_access_company      ON user_accesses (company_id);
CREATE INDEX idx_txlog_company            ON transaction_logs (company_id);
CREATE INDEX idx_txlog_location           ON transaction_logs (location_id);
CREATE INDEX idx_state_country            ON state_provinces (country_id);
CREATE INDEX idx_city_country             ON cities (country_id);
CREATE INDEX idx_city_state               ON cities (state_province_id);
CREATE INDEX idx_district_city            ON districts (city_id);
CREATE INDEX idx_neighborhood_district    ON neighborhoods (district_id);
CREATE INDEX idx_step_def_process_def     ON process_step_definitions (process_definition_id);
CREATE INDEX idx_loc_proc_config_location ON location_process_configs (location_id);
CREATE INDEX idx_loc_proc_config_process  ON location_process_configs (process_definition_id);
CREATE INDEX idx_step_config_loc_proc_config ON location_process_step_configs (location_process_config_id);
CREATE INDEX idx_step_config_step_def     ON location_process_step_configs (process_step_definition_id);
CREATE INDEX idx_audit_entity             ON configuration_audit_logs (entity_name, entity_id);
CREATE INDEX idx_audit_changed_by         ON configuration_audit_logs (changed_by_user_id);
CREATE INDEX idx_approval_step_config     ON approval_requests (step_config_id);
CREATE INDEX idx_approval_requested_by    ON approval_requests (requested_by_user_id);
CREATE INDEX idx_approval_reference       ON approval_requests (reference_type, reference_id);
CREATE INDEX idx_stock_company            ON stocks (company_id);
CREATE INDEX idx_stock_location           ON stocks (location_id);
CREATE INDEX idx_screen_fields_screen     ON screen_fields (screen_id);
CREATE INDEX idx_fbr_screen_field         ON field_behavior_rules (screen_field_id);
CREATE INDEX idx_fbr_location             ON field_behavior_rules (location_id);
CREATE INDEX idx_fbr_role                 ON field_behavior_rules (role_id);
CREATE INDEX idx_fbr_company              ON field_behavior_rules (company_id);
CREATE INDEX idx_fbr_country              ON field_behavior_rules (country_id);
CREATE INDEX idx_sl_zone_id                 ON storage_locations (zone_id);

-- ===================================================================
-- PHASE 9 — Drop helper functions (mapping table retained for cutover)
-- ===================================================================

DROP FUNCTION IF EXISTS wms_migrate_uuid_pk(TEXT, VARCHAR, TEXT);
DROP FUNCTION IF EXISTS wms_migrate_uuid_fk(TEXT, TEXT, VARCHAR);
DROP FUNCTION IF EXISTS wms_finalize_uuid_pk(TEXT);
DROP FUNCTION IF EXISTS wms_finalize_uuid_fk(TEXT, TEXT);
DROP FUNCTION IF EXISTS wms_audit_entity_type(VARCHAR);

COMMIT;
