package com.wms.events;

public enum EventType {
    STOCK_CHANGED,
    LOCATION_UPDATED,
    APPROVAL_CREATED,
    APPROVAL_RESOLVED,
    INTEGRATION_LOG_UPDATED,
    TASK_ASSIGNED,
    TASK_PROGRESS,
    TASK_COMPLETED,
    OPERATOR_STATUS_UPDATED,
    LOCATION_PROVISIONED,
    COMPANY_CHANGED
}
